### ISSUE TITLE
Implement for new lyrics-searcher with iconv-lite 

### ISSUE THREAD

**Issue by visualizeq** [seamless-medley/medley#12]

**Comment by vittee** [comment]
Implement a new function named `searchLyrics` with the same functionality as https://github.com/alias-rahil/lyrics-searcher/blob/main/src/lib/index.ts
But with `iconv-lite` in place of `iconv`, `zod` in plcce of `joi`

The implementation should be taking place below these lines.

https://github.com/seamless-medley/medley/blob/a269b672d42c09c6e24744b88045c576244d5dc6/packages/core/src/lyrics.ts#L195-L198

**Comment by vittee** [comment]
Done in 9d45191

I don't know why `lyrics-searcher`  uses `iconv` where it is not required, 
and after having a look at its code I can see that it is not well-written as it relies on literal string tokenzization.

So I decided to implement it my own way using `htmlparser2` (`lyrics-searcher`  also it via `html-to-text`) and `css-select` which I think yield a slightly better result.
